# Use Python Alpine para manter leve
FROM python:3.11-alpine

# Diretório de trabalho
WORKDIR /app

# Copiar apenas os arquivos necessários
COPY index.html .
COPY css ./css
COPY js ./js
COPY img ./img

# Expor porta 80
EXPOSE 80

# Iniciar servidor HTTP simples
CMD ["python", "-m", "http.server", "80"]
